### ISSUE TITLE
新功能需求：【删除内容自动化】

### ISSUE THREAD

**Issue by asseywang** [jxxghp/nas-tools#1669]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker 
## 你想要新增或者改进什么功能？

####1. 删除内容自动化
主要场景是：QB或其他种子文件删除（勾选了文件删除）这时候从QB反馈状态给Nas-Tools，通知embyAPI 删除媒体库硬连接的文件。

####2. 功能列表：
1. 种子删除，源文件删除或丢失检测
2. 自动删除硬连接
3. emby媒体库删除记录

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
没有，就是大量种子删除后媒体库也要删除一次，硬连接也要删除一次，比较麻烦。

请大佬评估是否能实现。

**Comment by link2fun** [comment]
参见 https://github.com/jxxghp/nas-tools/issues/1537
建议你不要用硬链接 去用软连接

**Comment by thsrite** [comment]
硬链接为了更好的刮削的同时不影响保种。
但有很多用户是观影的同时保种，不想看了就删除媒体库中的媒体，同时也想删除保种数据。

上面1537中说的，批量删除保种数据，我怎么知道批量删除的数据中哪些在媒体库中有，我还想看的，哪些是真要删除的呢？

**Comment by aerosmith2020** [comment]
> 



> 硬链接为了更好的刮削的同时不影响保种。 但有很多用户是观影的同时保种，不想看了就删除媒体库中的媒体，同时也想删除保种数据。
> 
> 上面1537中说的，批量删除保种数据，我怎么知道批量删除的数据中哪些在媒体库中有，我还想看的，哪些是真要删除的呢？

一段时间以后，批量删除种子的时候（eg.无法保种 due to 硬盘大小），无法得知哪些硬连接的媒体已经在jellyfin里被删除。最后还是要比对“硬连接文件夹”和“源文件夹” ，手动删除。当种子很多的时候，外加硬连接不同的分类，手动删除非常麻烦。这样会导致许多人选择这样的逻辑：删了qb种子和源文件，也想把硬连接所在“文件夹”删除。当然如果能从jellyfin删除，同时也从qb删除做种和源文件，这样的逻辑更好一些。毕竟这个工具是为了大家观影自动化，从jellyfin上删除，更人性化。

当然如果删jellyfin媒体文件，同时也想做种的话。那么这个功能我觉得很需要：让nastool给出哪些硬连接已经被删除，提供名单，这样以后qb/transmission删种的时候，会方便很多。

**Comment by jxxghp** [comment]
通过删种来同步删媒体库的，不知道你用这个软件是为了啥。这个功能不会实现。

通过删媒体库或软件内删除记录联动删种的，将来可能会实现，比较复杂。

**Comment by asseywang** [comment]
我来澄清一下这个需求。这里指的不是通过删除种子来删除媒体库，而是指删除种子时勾选了删除源文件，也就是媒体库这时候还能播放，原因是通过ns
 添加的硬连接不会跟着删除媒体源文件时删除，所以我要删除多个地方，才能清理媒体库，种子，源文件，硬连接。
硬连接貌似必须同时断开才会真的执行删除？

Mr Huang ***@***.***>于2022年10月19日 周三18:58写道：

**Comment by thsrite** [comment]
> 通过删种来同步删媒体库的，不知道你用这个软件是为了啥。这个功能不会实现。
> 
> 通过删媒体库或软件内删除记录联动删种的，将来可能会实现，比较复杂。

通过删媒体库或软件内删除记录联动删种的
这就可以
