### ISSUE TITLE
【bug】媒体检索失败，无法把下载的电影文件自动分类整理

### ISSUE THREAD

**Issue by yixiar** [jxxghp/nas-tools#602]
09:14:25 INFO - 【RMT】开始处理：/media/ori/疯狂动物城.Zootopia.2016.BD1080P.X264.AAC.English&Mandarin.CHS.Mp4Ba
09:14:25 ERROR - 【RMT】检索媒体信息出错！

一、背景：
（一）“推荐”栏目访问没有问题。
说明：1. 网络都可以正常访问。2. imdb key配置正确。
（二）设置了媒体库和同步目录。
将/media/ori/作为同步目录的源目录，将/media/link/movie作为了媒体库中的电影目录。
二、结果：
出现了开头处的错误提示。造成下载的视频文件无法识别、建立硬链接。整理的文件夹是空的。
三、其他情况
在左侧“媒体整理”栏目中，“手动识别”和“历史记录”中是空的，“TMDB缓存”中有内容。不知道正常不正常。

请问，无法自动分类的情况，是哪里设置错误了呢？

**Comment by Depressboy** [comment]
我也遇到了一样的问题，imdb的api秘钥配置过了，也做过科学上网了，但是还是识别不了
16:28:43 INFO - 【RMT】开始处理：/volume5/Medias/Transmission/失控玩家 Free Guy 2021 UHD 2160p Blu-ray HEVC TrueHD Atmos 7.1-Pete@HDSky
16:28:43 ERROR - 【RMT】检索媒体信息出错！
16:28:43 ERROR - 【SYNC】/volume5/Medias/Transmission 处理失败：检索媒体信息出错
16:28:43 INFO - 【RMT】开始处理：/volume5/Medias/Transmission/Rise.2022.REPACK.2160p.DSNP.WEB-DL.DDP5.1.Atmos.HDR.HEVC-CMRG
16:28:43 ERROR - 【RMT】检索媒体信息出错！
16:28:43 ERROR - 【SYNC】/volume5/Medias/Transmission 处理失败：检索媒体信息出错
16:28:43 INFO - 【RMT】开始处理：/volume5/Medias/Transmission/Hill.of.No.Return.1992.1080p.AMZN.WEB-DL.DDP2.0.H264-TJUPT.mkv
16:28:43 ERROR - 【RMT】检索媒体信息出错！

**Comment by pwcheng052** [comment]
也是一样的问题，手工把文件标题里面两个词之间的"."去掉后在TMDB网页上是可以检索到相应媒体的，不知是nostools的bug还是哪里没设置对，求高手指点
16:56:35 INFO - 【RMT】开始处理：/media/Video/Movie/Apollo.13.1995.MULTi.COMPLETE.UHD.BLURAY-NIMA4K
16:56:35 INFO - 【RMT】当前为蓝光原盘文件夹：/media/Video/Movie/Apollo.13.1995.MULTi.COMPLETE.UHD.BLURAY-NIMA4K
16:58:46 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?api_key=6037338f8bca06313e8695ff5945740b&query=Apollo+13&year=1995&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14f0962648b0>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
16:58:46 INFO - 【META】Apollo 13 以年份 1995 在TMDB中未找到电影信息!
17:00:57 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?api_key=6037338f8bca06313e8695ff5945740b&query=Apollo+13&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14f0977ca5c0>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
17:00:57 INFO - 【META】Apollo 13 以年份 在TMDB中未找到电影信息!
17:00:57 INFO - 【META】正在从TheDbMovie网站查询：Apollo 13 ...
17:00:58 INFO - 【META】Apollo 13 TMDB网站返回数据过多：14
17:01:28 INFO - 【META】推断关键字为：['13', 'apollo', 'apollo 13', 'ap'] ...
17:01:28 INFO - 【META】选择关键字为：13
17:01:28 INFO - 【META】开始辅助查询：13 ...
17:03:37 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/multi?api_key=6037338f8bca06313e8695ff5945740b&query=13&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14f0962656f0>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
17:03:37 WARN - 【RMT】Apollo.13.1995.MULTi.COMPLETE.UHD.BLURAY-NIMA4K 无法识别媒体信息！
17:03:37 ERROR - 【RMT】Apollo.13.1995.MULTi.COMPLETE.UHD.BLURAY-NIMA4K 无法识别媒体信息！
17:03:37 INFO - 【RMT】/media/Video/Movie/Apollo.13.1995.MULTi.COMPLETE.UHD.BLURAY-NIMA4K 处理完成，总数：1，失败：1

**Comment by Depressboy** [comment]
> 我也遇到了一样的问题，imdb的api秘钥配置过了，也做过科学上网了，但是还是识别不了 16:28:43 INFO - 【RMT】开始处理：/volume5/Medias/Transmission/失控玩家 Free Guy 2021 UHD 2160p Blu-ray HEVC TrueHD Atmos 7.1-Pete@HDSky 16:28:43 ERROR - 【RMT】检索媒体信息出错！ 16:28:43 ERROR - 【SYNC】/volume5/Medias/Transmission 处理失败：检索媒体信息出错 16:28:43 INFO - 【RMT】开始处理：/volume5/Medias/Transmission/Rise.2022.REPACK.2160p.DSNP.WEB-DL.DDP5.1.Atmos.HDR.HEVC-CMRG 16:28:43 ERROR - 【RMT】检索媒体信息出错！ 16:28:43 ERROR - 【SYNC】/volume5/Medias/Transmission 处理失败：检索媒体信息出错 16:28:43 INFO - 【RMT】开始处理：/volume5/Medias/Transmission/Hill.of.No.Return.1992.1080p.AMZN.WEB-DL.DDP2.0.H264-TJUPT.mkv 16:28:43 ERROR - 【RMT】检索媒体信息出错！

我的问题找到原因了
无法识别的问题解决了，我用的是群辉7套件方法安装的，停用套件再重新启用后可以正常识别整理了！！

**Comment by yixiar** [comment]
> 

太感谢了！
停用，再启用。就好了！！
再次感谢！！
Don't be Depressed :D
