### ISSUE TITLE
错误码256

### ISSUE THREAD

**Issue by KevinRocka** [jxxghp/nas-tools#973]
同步目录时候出现错误码256，希望知道是怎么回事，感谢。
![image](https://user-images.githubusercontent.com/12840710/188366991-35190a67-f607-44ce-965b-2343777baa58.png)

**Comment by fxqq** [comment]
但凡你看下wiki就知道，256是跨盘了，需要在同一个目录下

**Comment by colorsakura** [comment]
同样报错，但是进入docker 手动执行ln 成功。
![图片](https://user-images.githubusercontent.com/32534829/188488425-00dcd0e0-c195-40b9-9bee-b7ec0e70fe35.png)

![图片](https://user-images.githubusercontent.com/32534829/188488462-90b70138-72b4-42a9-8386-defe7c0698c4.png)

**Comment by colorsakura** [comment]
发现有成功的案例，失败的中，名字里都有‘（）’， 不知道是不是这个原因。

**Comment by KevinRocka** [comment]
> 但凡你看下wiki就知道，256是跨盘了，同步目录两个需要在同一个目录下

抱歉，我在wiki仔细找了找，还是没找到256错误码。我的下载目录和媒体库目录都是在一个磁盘目录下
![image](https://user-images.githubusercontent.com/12840710/188511368-09eeb8b3-dc23-46e5-8805-b487671d1662.png)
![image](https://user-images.githubusercontent.com/12840710/188511411-57daa0fc-d926-4f08-a403-9894c126e03a.png)

nas-tool设置的同步目录是
![image](https://user-images.githubusercontent.com/12840710/188511468-4a8e3de2-1611-41db-b75b-925eb6f4fbcf.png)
下载器设置的目录是
![image](https://user-images.githubusercontent.com/12840710/188511503-5e6da65f-2803-4da1-bdb4-d43cad16232b.png)

**Comment by jxxghp** [comment]
挂载的远程盘做硬链接？

**Comment by KevinRocka** [comment]
> 挂载的远程盘做硬链接？

没有，是Nas的盘符

**Comment by huluohu** [comment]
我看过wiki，然而并不跨盘---- 回复的原邮件 ***@***.***>发送日期2022年09月05日 21:33 ***@***.***> ***@***.******@***.***>主题Re: [jxxghp/nas-tools] 错误码256 (Issue #973)

但凡你看下wiki就知道，256是跨盘了，需要在同一个目录下



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/jxxghp/nas-tools/issues/973#issuecomment-1237038172",

"url": "https://github.com/jxxghp/nas-tools/issues/973#issuecomment-1237038172",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jxxghp** [comment]
如果是NAS上安装，你这个要么是Docker，因为套件的话路径不会是这样，一定会带/volume。
如果是Docker做过映射了，你这里明显跨盘了啊，都是两个共享文件夹。

![image](https://user-images.githubusercontent.com/51039935/188523772-38927a09-8c2b-4c0c-be9f-98b76f24d184.png)

**Comment by KevinRocka** [comment]
> 如果是NAS上安装，你这个要么是Docker，因为套件的话路径不会是这样，一定会带/volume。 如果是Docker做过映射了，你这里明显跨盘了啊，都是两个共享文件夹。
> 
> ![image](https://user-images.githubusercontent.com/51039935/188523772-38927a09-8c2b-4c0c-be9f-98b76f24d184.png)

知道了，我以为夸盘符是跨/volume1 和 /volume2 这种跨盘，没想到跨共享文件夹也是跨盼复
